---
title: "analysis"
output: pdf_document
date: "2025-11-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(lmerTest)
library(tidyverse)
```


```{r load data}
df_image <- read.csv("../../plot/processed_data_image.csv")
df_image$experiment_type <- "image"

df_text <- read.csv("../../plot/processed_data_text.csv")
df_text$experiment_type <- "text"

df <- bind_rows(df_image, df_text) %>%
  mutate(outcome_grouped = case_when(
    outcome <= 40 ~ '10-40',
    outcome == 50 ~ '50',
    outcome >= 60 ~ '60-90'
  ),
  outcome_grouped = factor(outcome_grouped,
                           levels = c('50',
                                      '10-40',
                                      '60-90')),
  event_type = factor(event_type, 
                      levels = c('gumball',
                                 'election')))


contrasts(df$outcome_grouped)

contrasts(df$event_type)
```


## Image analyses

### Might

```{r, cache=TRUE}

might_image <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id), 
                         family = binomial,
                         data = df %>% filter(utterance == 'might', experiment_type == 'image'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(might_image)
```


### Not

```{r, cache=TRUE}

not_image <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id), 
                         family = binomial,
                         data = df %>% filter(utterance == 'bare not', experiment_type == 'image'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(not_image)
```

### Probably

```{r, cache=TRUE}

probably_image <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id), 
                         family = binomial,
                         data = df %>% filter(utterance == 'probably', experiment_type == 'image'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(probably_image)
```




## Text analyses

### Might

```{r, cache=TRUE}

might_text <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id), 
                         family = binomial,
                         data = df %>% filter(utterance == 'might', experiment_type == 'text'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(might_text)
```


### Not

```{r, cache=TRUE}

not_text <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id),
                         family = binomial,
                         data = df %>% filter(utterance == 'bare not', experiment_type == 'text'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(not_text)

```

### Probably

```{r, cache=TRUE}

probably_text <- glmer(prob ~ outcome_grouped*event_type +
                           (1 + outcome_grouped*event_type | random_id), 
                         family = binomial,
                         data = df %>% filter(utterance == 'probably', experiment_type == 'text'),
                         glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000))) 

summary(probably_text)
```

